import { Amplify } from 'aws-amplify';
// In production, AMPLIFY_CONFIG will be populated by Amplify hosting
// In development, the file is generated by ampx sandbox

// Import outputs directly
// In development, this comes from ampx sandbox
// In production, Amplify hosting will create this file during build
import amplifyOutputs from '../../amplify_outputs.json';

/**
 * Configure the Amplify library
 * Call this function at the highest level of your application
 */
export function configureAmplify() {
  Amplify.configure(amplifyOutputs, { ssr: true });
} 